/**
 * Review Generation Data
 *
 * This module contains static data used to generate varied, human-sounding reviews.
 * Extracted from generate.ts to keep the API handler focused on business logic.
 */

/**
 * Reviewer identity and context for variety in generated reviews.
 * Combines identity, visit reason, and situational context into a single pool.
 * Not every entry has a visit reason — mirrors how real people write reviews.
 */
export const REVIEWER_CONTEXTS = [
  // Identity + Visit Reason (~80 entries)
  'a nurse who stopped in after a 12-hour shift',
  'a retired teacher killing time before a doctor\'s appointment',
  'a college freshman who wandered in on a dare from roommates',
  'a divorce attorney who needed somewhere quiet to decompress',
  'a mail carrier who ducked in to get out of the rain',
  'a night-shift worker stopping by on the way home at 7am',
  'a grad student who needed a break from the dissertation',
  'a personal trainer who came in after canceling a client',
  'a hotel guest who asked the concierge for a recommendation',
  'a freelance photographer between two shoots downtown',
  'a stay-at-home dad who finally got a few hours to himself',
  'a high school teacher on the first day of summer break',
  'a paramedic who came in still wearing scrubs',
  'a realtor who stopped by between open houses',
  'an accountant who came in to celebrate finishing tax season',
  'a librarian who wandered over on her lunch break',
  'a plumber who stopped in after finishing an early job nearby',
  'a speech therapist visiting from out of town for a conference',
  'a retired cop who comes by whenever he\'s in the neighborhood',
  'a college professor who came in to read papers somewhere new',
  'a UPS driver who popped in during his afternoon route',
  'a dog groomer who had a cancellation and some spare time',
  'a flight attendant with a long layover and nothing to do',
  'a wedding photographer recovering from a Saturday marathon',
  'a nanny who brought the kids while the parents were at work',
  'a stand-up comic who came in before a late-night open mic',
  'a construction foreman who stopped in on his lunch break',
  'a dental hygienist who came in on her day off',
  'an ER nurse dragged here by coworkers after the night shift',
  'a massage therapist who stopped by between appointments',
  'a physical therapist who came in after a long Saturday shift',
  'a sous chef on a rare day off exploring the neighborhood',
  'a long-haul trucker passing through for the first time',
  'a veterinarian who popped in while running errands nearby',
  'a hair stylist who came in after her last client of the day',
  'a software engineer who works remotely and needed to get out',
  'a firefighter who wandered in after his shift with his crew',
  'a tax attorney who stopped in to meet an old colleague',
  'a hospice nurse who needed somewhere calm after a hard week',
  'a crossing guard who came in right after her morning shift',
  'a landscape contractor stopping in after finishing a job nearby',
  'a social worker who needed a breather between home visits',
  'a food critic traveling incognito for a regional piece',
  'a marine biologist attending a conference a few blocks away',
  'a middle school principal who finally took a personal day',
  'a court reporter stopping in after a particularly long trial',
  'a military spouse new to the area and still figuring it out',
  'a PhD student celebrating finishing her qualifying exams',
  'a pharmacist who came in during a slow spell at the counter',
  'a first-year med student who just needed to sit somewhere',
  'a data analyst who works from home and needed human contact',
  'an immigration lawyer who came in to meet a client informally',
  'a city bus driver stopping in during his break at the depot',
  'a grocery store manager who came in on his day off',
  'a tattoo artist stopping by between appointment blocks',
  'a respiratory therapist on the first day of her vacation',
  'a trauma surgeon who came in after a brutal on-call weekend',
  'a speech pathologist who came in with a group of coworkers',
  'a middle-aged electrician waiting for parts to be delivered',
  'a hospice chaplain stopping in after a very difficult morning',
  'a public defender who came in to clear her head between cases',
  'a UX designer who dragged herself out of the house to think',
  'a crossing guard who started coming here after a co-worker recommended it',
  'an exhausted new parent whose toddler had just gone down for a nap',
  'a recently widowed retiree trying to get out of the house more',
  'a high school senior who came in the day after graduation',
  'a youth soccer coach who stopped in after Saturday morning practice',
  'a substitute teacher who finally got called in after weeks of waiting',
  'an ER doctor who came in during the first calm weekend in months',
  'a night security guard stopping in on the way home',
  'a part-time Lyft driver in between rides with time to kill',
  'a nonprofit director who came in after a grant deadline passed',
  'a marine vet adjusting to civilian life and exploring the area',
  'a pediatric dentist who came in while her car was in the shop',
  'a homeschool mom who planned a field-trip day for herself',
  'a newly retired postal worker who didn\'t know what to do with Tuesdays',
  'a daycare teacher who came in after the kids went home',
  'a hospice volunteer stopping by after finishing her weekly rounds',
  'a cellist who came in between rehearsal and the evening performance',
  'a court-appointed guardian who stopped in after a tough hearing',
  'a hospital chaplain who just needed somewhere quiet to sit',

  // Identity Only — No Visit Reason (~60 entries)
  'someone who doesn\'t usually leave reviews',
  'a creature of habit who hates trying new places',
  'not exactly an adventurous person when it comes to this stuff',
  'a self-described homebody who got talked into going out',
  'a total skeptic who was fully prepared to be disappointed',
  'someone whose bar is extremely low after recent experiences',
  'a person who usually just lurks and never posts anything',
  'not the type to ever complain but this time made an exception',
  'someone who read every review before deciding to come',
  'a person with strong opinions about this kind of place',
  'an extremely picky eater with strong opinions',
  'a former industry worker who notices everything',
  'a self-proclaimed connoisseur of the mediocre',
  'someone who spent 20 minutes reading reviews before deciding',
  'a chronic overthinker who almost talked herself out of going',
  'an introvert who took a deep breath before walking in',
  'a local who had walked past this place a hundred times',
  'someone who almost didn\'t come in because of the parking',
  'a regular at a competitor who decided to branch out',
  'a person who judges a place in the first 30 seconds',
  'a detail-obsessed type who notices when things are off',
  'a retired quality inspector who can\'t turn it off',
  'someone visiting their hometown for the holidays',
  'a first-generation college student home for winter break',
  'an only child used to doing things solo',
  'a serial solo diner who actually prefers it this way',
  'a night owl who keeps unconventional hours',
  'a chronic insomniac who just wanted to be somewhere',
  'a morning person who shows up embarrassingly early everywhere',
  'a reformed picky eater still working through the list',
  'someone who got dragged along and ended up having opinions',
  'a plus-one who hadn\'t planned on being anywhere today',
  'a very opinionated person who finally has a platform',
  'someone celebrating a minor personal victory',
  'a people-pleaser who is trying to be more honest in reviews',
  'a recovering perfectionist who is learning to lower standards',
  'an over-researcher who had already looked at the menu twice',
  'a spontaneous person pretending to be more spontaneous than they are',
  'a local who is deeply suspicious of anything hyped online',
  'a tourist who refuses to eat anywhere with a QR-only menu',
  'a remote worker who judges every place by its WiFi first',
  'someone whose therapist suggested getting out more',
  'a plant parent who applies the same care standards everywhere',
  'a true crime podcast listener who is used to analyzing details',
  'a recovering workaholic on a mandated staycation',
  'an overthinker who almost left before being seated',
  'a deeply indecisive person who finally committed',
  'someone who had a Groupon and almost forgot to use it',
  'a loyalty card hoarder who lost the old one and started over',
  'a frugal person who waited for a deal before trying it',
  'a person who photographs everything before touching anything',
  'a minimalist who has opinions about clutter in unexpected places',
  'a budget traveler stretching every dollar on the road',
  'a first-timer who came in completely cold with no research',
  'a repeat visitor who has developed strong feelings over time',
  'an ambivalent local who finally decided to form an opinion',
  'a homesick expat back for a short visit',
  'a newly single person figuring out where to go alone',
  'someone going through a mild existential phase',
  'an overwhelmed parent who came here alone for the first time',

  // Pure Situation/Context — No Explicit Identity (~60 entries)
  'was killing time while my car was getting fixed next door',
  'got here way too early and had nowhere else to go',
  'was in the area for a meeting that got canceled last minute',
  'stumbled in because the place I wanted was fully booked',
  'came in out of the rain and ended up staying longer than planned',
  'my GPS sent me here instead of where I was actually going',
  'was on hold with insurance for 45 minutes and needed to sit',
  'waited here while a friend got a haircut across the street',
  'had a gift card that was about to expire',
  'was early for a first date and needed somewhere to collect myself',
  'came here because everywhere else had a 45-minute wait',
  'ended up here after a long walk with nowhere in mind',
  'came in to use the restroom and then felt obligated to order',
  'was having a genuinely terrible week and just needed this',
  'came here specifically because my ex hated this kind of place',
  'was avoiding going home for as long as possible',
  'had a craving I couldn\'t shake and this was the closest option',
  'it was raining and I saw open seats through the window',
  'came in because a stranger on the street said it was great',
  'came here because I drove past it every day and finally stopped',
  'was meeting someone who never showed up, so I just stayed',
  'was waiting for a prescription to be filled around the corner',
  'had an hour before my flight and stumbled on this place',
  'wandered over after an appointment ran short',
  'had no particular plan and just ended up here',
  'got stood up and decided to make the best of the reservation',
  'came in with a migraine and just needed somewhere dim and quiet',
  'was on the phone with my mom and needed to look busy',
  'came here because someone online said it was underrated',
  'had a long wait at a government office and needed to recover',
  'was avoiding a difficult phone call I kept putting off',
  'stopped in because the line outside looked short for once',
  'came here because I was too hungry to walk any further',
  'was early for a funeral and needed somewhere to sit',
  'came in completely on impulse walking back from somewhere else',
  'my friend group couldn\'t agree on anything and we landed here',
  'tagged along with someone who\'d been talking about it for weeks',
  'came here for someone\'s birthday and had zero expectations',
  'was dragged here by a coworker and ended up grateful',
  'went on a whim after a late-night recommendation from a stranger',
  'had no idea what I was walking into and went for it anyway',
  'came in because I needed to sit somewhere that wasn\'t home',
  'was celebrating something small that felt big in the moment',
  'stopped in on the way back from something that went sideways',
  'needed somewhere to draft an uncomfortable email in peace',
  'came in because I just got some very good news and wanted to mark it',
  'was taking a long walk to process a hard conversation',
  'stopped in because I hadn\'t done anything nice for myself in weeks',
  'came here because I was running on three hours of sleep and needed help',
  'wandered in during an aimless afternoon with no destination',
  'came here after realizing I hadn\'t left the house in three days',
  'ended up here after a detour that turned into an adventure',
  'stopped in because my usual place was closed for some reason',
  'came in during a lunch break that was running very short',
  'was here with someone on a third date, trying to seem low-key',
  'came in because my phone died and I needed an outlet and a reason to stay',
  'was here working up the nerve to send an important message',
  'stopped in because nothing else sounded right and this did',
  'came here as a reward to myself after finishing something hard',
  'was on a solo trip and tired of eating alone in hotel rooms',
] as const

/**
 * Opening phrases to force variety in reviews.
 * Each review starts with one of these to avoid repetitive beginnings.
 */
export const REVIEW_OPENERS = [
  // Casual conversation starters
  "Ok so",
  "Honestly",
  "Not gonna lie",
  "Real talk",
  "Listen",
  "Look",
  "Alright so",
  "Here's the thing",
  "So basically",
  "Let me tell you",
  "I gotta say",
  "Gotta be honest",
  "Truth be told",
  "For real though",
  "No cap",
  "Straight up",
  "Lowkey",
  "Highkey",
  "Legit",

  // Time-based openers
  "Finally",
  "Just",
  "Recently",
  "Last week",
  "Yesterday",
  "The other day",
  "This morning",
  "Tonight",
  "Earlier today",
  "A few days ago",
  "Been meaning to",
  "After months of",
  "Took me forever to",

  // Action-based openers
  "Came here",
  "Stopped by",
  "Dropped in",
  "Swung by",
  "Checked out",
  "Tried",
  "Just tried",
  "Had to try",
  "Decided to try",
  "Walked in",
  "Popped in",
  "Grabbed",
  "Got",
  "Ordered",
  "Picked up",

  // Social/referral openers
  "My friend",
  "My coworker",
  "My partner",
  "My mom",
  "Someone told me",
  "Heard about",
  "Everyone kept saying",
  "People weren't lying",
  "The reviews were right",
  "Yelp said",
  "Google led me here",
  "TikTok made me",
  "Instagram brought me",
  "A friend dragged me",
  "My bf/gf recommended",

  // Discovery openers
  "Found this",
  "Stumbled upon",
  "Discovered",
  "Walked past",
  "Drove by",
  "Never noticed",
  "Hidden away",
  "Tucked in",
  "Right around the corner",
  "Down the street",

  // Emotion/reaction openers
  "So glad",
  "Super happy",
  "Pleasantly surprised",
  "Wasn't expecting",
  "Didn't think",
  "Who knew",
  "Can't believe",
  "Mind blown",
  "Impressed",
  "Wow",
  "Whoa",
  "Damn",
  "Man",
  "Dude",
  "Yo",
  "Y'all",
  "Omg",
  "Bruh",

  // Skeptic/convert openers
  "I was skeptical",
  "Wasn't sure",
  "Had my doubts",
  "Almost didn't",
  "Nearly skipped",
  "Hesitated but",
  "Took a chance",
  "Gave it a shot",
  "Worth the risk",

  // Context openers
  "After a long day",
  "On my lunch break",
  "Needed something",
  "Was craving",
  "In the mood for",
  "Looking for",
  "Searching for",
  "Hungry and",
  "Starving so",

  // Qualifier openers
  "Quick review",
  "Short version",
  "Long story short",
  "TLDR",
  "In a nutshell",
  "Bottom line",
  "Main takeaway",

  // Casual intros
  "This place",
  "These guys",
  "The team here",
  "The folks here",
  "The people",
  "The staff",
  "The owner",

  // Emphasis openers
  "Actually",
  "Seriously",
  "Genuinely",
  "Truly",
  "Really",
  "Definitely",
  "Absolutely",
  "Can confirm",
  "100%",
  "10/10",

  // === NEW OPENERS ===

  // Exclamations & Reactions
  "Holy moly",
  "Oh wow",
  "Oh man",
  "Oh my",
  "Whew",
  "Yikes",
  "Oof",
  "Sheesh",
  "Woof",
  "Ugh",
  "Aw man",
  "Hot damn",
  "Good lord",
  "Sweet baby",
  "Oh hell yes",

  // Gen Z / Internet slang
  "Slay",
  "It's giving",
  "No because",
  "Not me",
  "periodt",
  "Bestie",
  "Ate and left",
  "The way I",
  "POV:",
  "Main character",
  "We love to see",
  "Living for this",
  "Understood the assignment",
  "Rent free",
  "No thoughts just",

  // Millennial openers
  "I can't even",
  "So I may have",
  "Adulting win",
  "Treat yourself",
  "Self-care Sunday",
  "Date night and",
  "Spoiler alert",
  "Plot twist",
  "Not all heroes",
  "Goals honestly",
  "Obsessed doesn't cover",
  "Crying in happy",
  "Unironically love",
  "Ironically great",
  "Hot take but",

  // Blunt / Deadpan
  "Fine. Great.",
  "It is what",
  "Whatever you think",
  "Solid. Moving on.",
  "Exists. Works. Bye.",
  "Did the thing.",
  "Ate. Left. Repeat.",
  "Came. Saw. Conquered.",
  "No complaints honestly",
  "Simple review:",
  "Bluntly speaking",
  "Not much to",
  "Nothing special but",
  "Perfectly average and",
  "Adequate at best",

  // Questions as openers
  "Why did no one",
  "How is this",
  "Where has this",
  "When did this",
  "What is happening",
  "Why aren't more people",
  "Have you ever",
  "Does anyone else",
  "Am I crazy",
  "Is it just",
  "Can we talk",
  "Did I really",
  "How have I",
  "Who let them",
  "Remember when",

  // Numbers / Ratings as openers
  "Five stars easily",
  "Four stars because",
  "Three stars but",
  "Two visits in",
  "First time here",
  "Second time back",
  "Third visit and",
  "Tenth time maybe",
  "One word:",
  "Two things:",
  "Three reasons why",
  "My third visit",
  "Came twice already",
  "Been here five",
  "Fourth trip here",

  // Seasonal / Time-based
  "Perfect summer spot",
  "Great winter vibe",
  "Holiday season and",
  "Spring afternoon well",
  "Fall vibes here",
  "Rainy day rescue",
  "Snow day treat",
  "Hot day solution",
  "Weekend trip winner",
  "Friday night pick",
  "Saturday morning run",
  "Sunday funday approved",
  "Midweek escape honestly",
  "Post-work stop",
  "Holiday gathering spot",

  // Emotional / Mood-based
  "Was having a",
  "Bad day turned",
  "Needed a win",
  "Feeling down so",
  "Celebrating today and",
  "Treating myself because",
  "Rewarded myself with",
  "Comfort food moment",
  "Emotional support meal",
  "Stress eating led",
  "Sad girl hours",
  "Happy place unlocked",
  "Peak happiness achieved",
  "Cozy and content",
  "Simply delighted honestly",

  // Action verbs to start
  "Drove forty minutes",
  "Walked twenty blocks",
  "Biked across town",
  "Took the train",
  "Parked and prayed",
  "Waited in line",
  "Reserved a spot",
  "Booked ahead thankfully",
  "Showed up early",
  "Arrived right at",
  "Rushed here after",
  "Sprinted from work",
  "Snuck away for",
  "Escaped the office",
  "Ducked in for",

  // Comparison starters
  "Better than expected",
  "Worse than hoped",
  "Just like they",
  "Nothing like the",
  "Similar vibes to",
  "Reminds me of",
  "Way better than",
  "Almost as good",
  "Blows everything else",
  "Top three ever",
  "Best in the",
  "Better than my",
  "Comparable to downtown",
  "Puts chains to",
  "Makes other places",

  // Location references
  "In the neighborhood",
  "Nearby so figured",
  "Walking distance from",
  "Right next to",
  "Across from the",
  "In that little",
  "Strip mall gem",
  "Plaza find honestly",
  "Off the highway",
  "Downtown location rocks",
  "Suburban surprise here",
  "Local favorite finally",
  "Neighborhood staple and",
  "Corner spot vibes",
  "Side street find",

  // Formal / Older tone
  "I must say",
  "I will note",
  "I should mention",
  "It should be",
  "Allow me to",
  "In my experience",
  "Speaking from experience",
  "As a regular",
  "As someone who",
  "From my perspective",
  "In all fairness",
  "To be fair",
  "I must admit",
  "It bears mentioning",
  "Without hesitation",

  // Mid-sentence fragments
  "And the thing is",
  "But here's what",
  "So the deal",
  "Because honestly",
  "Because look",
  "Since we're here",
  "Since I'm talking",
  "While I'm at",
  "Not that it",
  "Even if you",
  "Despite the",
  "Regardless of what",
  "Aside from the",
  "Beyond the hype",
  "Past the line",

  // Social media / Referral starts
  "Reddit brought me",
  "Facebook group said",
  "Twitter hyped this",
  "Saw this on",
  "Reel stopped me",
  "Story made me",
  "Post convinced me",
  "Ad actually worked",
  "Influencer was right",
  "Blogger recommended this",
  "Newsletter mentioned it",
  "Podcast said go",
  "YouTube review checked",
  "Comment section convinced",
  "Review thread found",

  // Group/Company context
  "Group of six",
  "Solo this time",
  "Date night required",
  "Girls trip stop",
  "Guys night out",
  "Family dinner here",
  "Work lunch today",
  "Team outing pick",
  "Birthday dinner choice",
  "Anniversary spot chosen",
  "First date venue",
  "Brought the whole",
  "Just the two",
  "Three of us",
  "Large party and",

  // Skeptic-to-convert arc
  "Thought it was",
  "Expected to hate",
  "Ready to leave",
  "Almost walked out",
  "Doubted everything but",
  "Assumed it was",
  "Figured it'd be",
  "Guessed it was",
  "Predicted disappointment but",
  "Wrong about this",
  "Owe them an",
  "Had to apologize",
  "Eating my words",
  "Surprised myself here",
  "Converted officially now",

  // Exclamatory enthusiasm
  "Incredible honestly",
  "Phenomenal experience here",
  "Spectacular and then",
  "Unreal how good",
  "Legitimately amazing",
  "Genuinely fantastic",
  "Absolutely wild how",
  "Wildly good honestly",
  "Insanely solid pick",
  "Outrageously good here",
  "Ridiculously worth it",
  "Stupidly good honestly",
  "Embarrassingly obsessed now",
  "Dangerously addicted to",
  "Criminally underrated spot",

  // Casual connectors
  "So anyway",
  "Anyway though",
  "Moving on but",
  "Oh also",
  "Also worth noting",
  "Side note:",
  "Fun fact:",
  "Quick note:",
  "Important detail:",
  "Key thing here",
  "Worth mentioning that",
  "Oh and another",
  "Forgot to say",
  "Almost missed this",
  "Nearly forgot but",

  // Return visit angle
  "Back again obviously",
  "Couldn't stay away",
  "Had to return",
  "Came back already",
  "Second review because",
  "Updating my review",
  "Still coming back",
  "Regular now honestly",
  "Monthly visit locked",
  "Weekly stop now",
  "Daily if I",
  "Would live here",
  "Moving in mentally",
  "Basically a regular",
  "They know my",

  // Unexpected discovery
  "Randomly found this",
  "Complete accident but",
  "Wrong turn win",
  "GPS error blessing",
  "Lost and then",
  "Detour led here",
  "Detoured and wow",
  "Wandering paid off",
  "Exploring and found",
  "Stumbled in honestly",
  "Ducked in from",
  "Sheltered here and",
  "Accident turned favorite",
  "Happy accident honestly",
  "Luck brought me",

  // Understated / Dry
  "It exists and",
  "Showed up hungry",
  "Left not hungry",
  "Mission accomplished here",
  "Food was food",
  "Did its job",
  "Served its purpose",
  "Can't argue with",
  "Zero complaints filed",
  "No notes honestly",
  "Checks all boxes",
  "Hits the marks",
  "Does what it",
  "What it says",
  "Exactly as advertised",
] as const

/**
 * Example real human reviews to guide the AI model.
 * These demonstrate the casual, authentic tone we want.
 */
export const EXAMPLE_HUMAN_REVIEWS = [
  // Minimal effort / terse
  "good place tbh",
  "came back again lol",
  "yeah its fine i guess",
  "solid. will return.",
  "not bad at all",
  "does the job",
  "massive W for this place honestly",
  "love this place fr fr",
  "LOVE this place so much!!",
  "10/10 no complaints",
  "good. clean. nice people. done.",
  "yeah it's good",
  "came here. liked it. end of review.",
  "fine place, did what i needed",
  "no issues. would go back.",
  "Worth it.",
  "really good honestly",
  "my new spot",
  "the vibes in here are right",
  "this place slaps every single time",

  // Non-native English speakers
  "the service is make me very happy, I am go here many time and every time is good",
  "very much good place, the staff help me very nice and I feel welcome when I come",
  "I am go here with my family and we all like it, is very good and the people are kind",
  "this place is so much better than I expect, I think maybe not good but then I am surprise",
  "the worker help me very nice, my english not so good but they understand me and help anyway",
  "is very good place!! I reccomend to all my friends, they go and say also very good thank you",
  "I am come here three time now and every time the service is make me happy, is very consistent",
  "they help me very nice and I feel like they really care, is not just for the money you know",
  "good place!! staff very friendly and the result is what I want. I will come again definately",
  "my husband and me we come here and we think is very nice. the person help us good and we are happy",
  "I am not the person who give review but this place is so good I must say something. they very kind and very professional and I feel respect when I am there. is hard to find this in my experience.",
  "I am not speak English very good but I want say this place help me very much. the person there is patient and explain everything slow for me and I understand. very good service.",
  "I bring my mother here, she not speak English, and the staff is very kind to her. they try hard to help her and she feel comfortable. is very good place for everyone.",

  // Common native speaker grammar mistakes
  "should of went sooner honestly, me and my wife been putting this off for months and we regret waiting",
  "their the best in this part of town, no question about it",
  "me and my husband loved it so much we already booked again",
  "could of been better in a couple small ways but still good overall, would come back",
  "your gonna love this place, trust me on this one",
  "me and my coworkers come here on lunch breaks now, we should of found this place way earlier",
  "the staff here are really good at there jobs and they make you feel comfortable",
  "I should of listened to my sister sooner, she been telling me about this place for like a year",
  "me and my kids come here sometimes and their always patient with us which i appreciate",

  // Casual / normal with slang
  "ok so I came here with no expectations and honestly? left kinda shook by how smooth everything went",
  "Stopped by on a whim while I was in the area and now I can't stop thinking about it",
  "Not gonna lie I had to talk myself into going and now I'm annoyed it took me this long.",
  "My coworker mentioned it in passing like eight months ago and I finally got around to it. She was not wrong.",
  "Took a chance on this place after everything else in the area let me down. Zero regrets.",
  "The person who helped me clearly gave a damn and you can tell the difference when someone does.",
  "nothing crazy just solid and consistent which is honestly all i want",
  "been here maybe five times. same good experience every time. thats the whole review",
  "came in with my mom and she loved it so. that's the review",
  "first time here and already planning when i can come back lol",
  "ok wow. wasn't ready for how good this was. pleasantly blindsided.",
  "came here bc someone in my neighborhood facebook group mentioned it and those recommendations are usually hit or miss but this one was a hit",
  "stumbled in during a walk with no plan and now I have a plan which is to come back here as much as possible",
  "honestly refreshing to find a place where the people working there seem to actually want to be there",
  "me and my sister tried this place last month and now she wants to come every time we hang out which is honestly fair",

  // Articulate but casual
  "Came here for someone's birthday with zero expectations and ended up being the most enthusiastic person about it. Embarrassing but accurate.",
  "The wait was real but honestly the experience on the other side of it was worth the annoyance. I hate waiting so that's saying something.",
  "I've been recommending this place to literally everyone I know for the past three weeks. My friends are tired of hearing about it.",
  "Walked in kind of nervous because I always get nervous at new places and the staff immediately made me feel like I belonged there.",
  "Been coming here for about a year and a half and they've stayed consistent the whole time. That's hard to do and I appreciate it.",
  "Honestly thought places like this didn't exist anymore. Places that just do the thing well without making a production of it.",
  "My friend group has a running debate about where to go and this is the first place we've unanimously agreed on. Write that down.",
  "Clean, professional, kind. That's the whole thing and they nail it every time I've been.",
  "I came in with a kind of complicated situation and they sorted it out without making me feel stupid about it. Huge.",
  "the lady at the front has remembered my name for months now and I genuinely don't know how she does that but it makes every visit feel good",
  "I travel through here for work and this is always the first stop I make when I'm in town. Says a lot.",
  "I don't leave reviews. Like ever. This place made me leave a review. That should tell you everything.",
  "Straight up one of the best decisions I've made this month and my month has had some decisions in it.",
  "I came, I got helped, I left happy. Honestly all I can ask for.",
  "The details here are right. Not one big wow thing, more like fifteen small things that all add up.",

  // Mixed / slightly negative but positive overall
  "Three stars because the wait time was longer than it needed to be but honestly everything else was great so maybe three and a half",
  "Good but I've had slightly better elsewhere, not complaining though. Would still come back, staff is genuinely nice.",
  "it's fine. nothing blew me away but nothing went wrong either. comfortable middleground i guess",
  "decent place, could use a little more communication on wait times but the actual service was solid so",
  "not bad. not great. fine.",
  "I mean... it was ok? kinda expected a little more based on reviews but maybe I caught them on an off day",
  "so the thing is this place is actually really good but the one person working the desk was a little scattered, everything else made up for it though",
  "The price was higher than I hoped but also the quality matched the price so I can't really be mad about it.",
  "waited longer than expected but they were upfront about it which made all the difference, i can handle a wait if someone just tells me about it",

  // ALL CAPS enthusiasm
  "THE STAFF HERE IS SO GOOD omg I walked in anxious and walked out completely taken care of, 5 stars easy",
  "BEST experience I've had in a really long time. The person helping me went out of their way and I won't forget it.",
  "SO GLAD I finally came here. been walking past this place for two years like an idiot",
  "this place NEVER disappoints and trust me I've given it plenty of chances to",
  "honestly??? obsessed. that's the whole review. obsessed.",

  // Rambly / stream-of-consciousness
  "ok so i come in here like every other week at this point and i keep meaning to write a review and finally doing it, bottom line: great place, really consistent, the staff is friendly and seems to actually like being there which is rare, the only thing i'd say is that it can get crowded on weekends so go during the week if you can, that's my main tip, otherwise no complaints",
  "found this place by accident when my usual spot was closed and i ended up liking it way more than my original plan which was annoying in the best way possible, now it's basically my primary spot and my backup spot has become my main spot so thats how that happened",
  "i feel like i need to explain something which is that i don't usually do this, like i've written maybe three reviews in my life, but this place was good enough that it felt wrong not to say something, so here i am saying something, basically just go, trust me, it's good, the people are nice and they know what they're doing and it doesn't feel like they're rushing you out",
  "came here after a genuinely brutal week and i don't know maybe my guard was down but everything about this visit just felt exactly right, the person helping me was warm without being over the top, the whole thing was efficient without feeling rushed, and i left in a better mood than i'd been in all week, that's not nothing",
  "my partner and i were in the area and had an hour to kill so we figured why not, and then we ended up staying longer than we planned because we were just comfortable there, and now we keep talking about going back even though it's not exactly close to us, so yeah, good place",

  // Misc real-feeling
  "so ok my expectations were VERY low based on a bad experience somewhere else and I am happy to report I was completely wrong to be worried",
  "my dad is the hardest person to please in any situation and he asked me when we could go back. unprecedented.",
  "it was raining and I needed somewhere to go and this place turned into the highlight of my whole week which is funny",
  "Yelp brought me here and for once the internet was right.",
  "This is the kind of place that makes you feel like a person and not just a number and I don't take that for granted anymore.",
  "so i was in the area killing time before an appointment and ducked in and now i kind of wish i hadn't because i'm gonna want to come back constantly",
  "I've sent probably four people here in the last month. All of them have texted me to say thank you. Says everything.",
  "No complaints from me and I am a person who usually has complaints.",
] as const

/**
 * Ultra-short examples for very brief reviews.
 * Used when the length profile is "ultra-short" (6-12 words).
 */
export const ULTRA_SHORT_EXAMPLES = [
  "Finally tried it, not disappointed",
  "My new go-to honestly",
  "The hype is real ngl",
  "Better than expected tbh",
  "Came for the reviews, staying for the food",
  "Worth the wait fr",
  "10/10 would come back",
  "Exactly what I needed today",
  "Can't complain at all",
  "Slaps every time",
  "Pretty decent actually",
  "They know what they're doing",
  "Hit the spot perfectly",
  "This place gets it",
  "Yep. Coming back",
  "A+ vibes here",
  "No notes tbh",
  "Just what I was looking for",
  "Lived up to expectations",
  "Good find right here",
  "Why did I wait so long",
  "Yeah this place is legit",
  "Consider me a regular now",
  "Take my money already",
  "Instant favorite",
  "Where has this been all my life",
  "Nailed it",
  "Didn't disappoint",
  "Checks all the boxes",
  "I'm sold",
] as const

/**
 * Length profiles for reviews with their weights.
 * Skews shorter — most real Google/Yelp reviews are brief.
 *
 * Distribution:
 * - ultra-short: 25% - Very brief one-liners
 * - short: 35% - 1-2 sentences, most common
 * - medium: 25% - 3-4 sentences
 * - long: 10% - 5-6 sentences
 * - extended: 5% - Full story reviews, rare
 */
export const LENGTH_PROFILES = [
  { type: 'micro', instruction: '3-6 words only. A tiny gut reaction.', weight: 3 },
  { type: 'ultra-short', instruction: '6-12 words only. Just a quick one-liner reaction.', weight: 4 },
  { type: 'short', instruction: '1-2 sentences. Brief but gets the point across.', weight: 6 },
  { type: 'medium', instruction: '3-4 sentences. Standard review length.', weight: 4 },
  { type: 'long', instruction: '5-6 sentences with some detail.', weight: 2 },
  { type: 'extended', instruction: '2 short paragraphs. Tell a story about the experience.', weight: 1 },
] as const

export type LengthProfile = typeof LENGTH_PROFILES[number]

/**
 * Quirk probabilities for adding human-like imperfections.
 *
 * Each quirk has a probability of being added to make reviews more authentic.
 * Lower probabilities = rarer quirks that would look suspicious if overused.
 */
export const REVIEW_QUIRKS = {
  /** 25% chance - Casual contractions */
  CASUAL_CONTRACTIONS: { probability: 0.25, instruction: 'use "gonna", "kinda", "gotta", or "wanna"' },
  /** 15% chance - Minor typos (lower probability to avoid looking fake) */
  MINOR_TYPOS: { probability: 0.15, instruction: 'include a minor typo like "teh", "definately", "resturant", or missing apostrophe' },
  /** 30% chance - Ellipsis or em-dash mid-thought */
  TRAILING_PUNCTUATION: { probability: 0.3, instruction: 'use "..." mid-thought' },
  /** 25% chance - Common abbreviations */
  ABBREVIATIONS: { probability: 0.25, instruction: 'abbreviate something like "bf", "bc", "tbh", "imo", or "ngl"' },
  /** 20% chance - Starting sentences with conjunctions */
  CONJUNCTION_STARTS: { probability: 0.2, instruction: 'start a sentence with "And" or "But" or "So"' },
  /** 10% chance - Lowercase "i" (very rare, would be suspicious if common) */
  LOWERCASE_I: { probability: 0.1, instruction: 'use lowercase "i" instead of "I" once' },
} as const

/**
 * Keyword selection probability.
 * 60% chance of selecting 1 keyword, 40% chance of selecting 2.
 * This creates natural variation - most reviews mention 1 thing.
 */
export const KEYWORD_SELECTION = {
  /** Probability of selecting just 1 keyword (vs 2) */
  SINGLE_KEYWORD_PROBABILITY: 0.6,
} as const
